// AUTO-GENERATED by release.js — do not edit manually
// Source: index.html v6.4.3
// Rebuilt: 2026-05-01T14:40:18.737Z
'use strict';

// ── STATE DEFAULTS ────────────────────────────────────────
var S = {
  // Model
  params:8, modelLabel:'Llama 3.1 8B', attn:'gqa', prec:'fp16',
  numKvHeads:8, numHeads:32, headDim:128, numLayers:32, hfId:null,
  kvLayers:null,        // effective unique KV layers (Gemma 4 / SSM hybrid) — null = use numLayers
  activeExperts:null,   // MoE active experts per token — null = not MoE
  totalExperts:null,    // MoE total experts
  // Architecture-specific KV fields (populated by HF Lookup)
  kvArchType:null,      // null | 'standard' | 'hybrid_sliding' | 'hybrid_ssm' | 'mla' | 'moe'
  kvGlobalLayers:null,  // hybrid_sliding: unique global attention layers
  kvSlidingLayers:null, // hybrid_sliding: unique sliding window layers
  slidingWindow:null,   // hybrid_sliding: window size in tokens
  globalKvHeads:null,   // hybrid_sliding: KV heads for global layers (if different)
  globalHeadDim:null,   // hybrid_sliding: head dim for global layers (if different)
  isMoE:false,          // MoE flag
  kvLoraRank:null,      // MLA: compressed KV dimension (DeepSeek V2/V3)
  qkRopeHeadDim:null,   // MLA: rope head dim added to latent
  // Users
  users:1000, ctx:4, isl:2000, osl:200, ctxMax:128, hitrate:0.0, concRate:0.20, cacheType:'persistent',
  // Inference
  fw:'vllm', mode:'std', tp:1, kvPrec:'fp16',
  pfGpus:1, dcGpus:1,
  // GPU
  gpuName:'H200', gpuVram:141,
  // Cost
  dep:'cloud', cloudRate:3.00, disc:0,
  hwCost:25000, amort:5, kwh:0.10, infraPct:0, opexPct:0,
  // Hybrid
  hGpus:2, hRun:16, hHw:25000, hGpuName:'H100', hUtil:0.30, hAmort:5, hKwh:0.10,
  hSplit:null, // null = auto from utilisation; number = manual override
  hDedRate:18000, // dedicated node $/mo for 8-GPU node (CoreWeave default)
  hDedGpus:8,    // GPUs per dedicated node
  // Explorer
  expNV:true, expAMD:true, axX:'vram', axY:'tpp', axB:'usdPer100Tpp',
};;

// ── FLEET STATE ───────────────────────────────────────────
var SF = {
  totalUsers: 1000,
  queriesPerUserPerDay: 100,
  concurrencyFactor: 0.10,
  engCost: 50000,
  tiers: [
    {name:'Simple queries',model:'Llama 3.1 8B',params:8,layers:32,kvHeads:8,headDim:128,attn:'gqa',trafficPct:60,avgInputTok:200,avgOutputTok:100,ctx:4,gpuName:'H100',gpuVram:80,prec:'fp16',tp:1,apiModel:'Claude 3.5 Haiku',open:false},
    {name:'Standard queries',model:'Llama 3.1 70B',params:70,layers:80,kvHeads:8,headDim:128,attn:'gqa',trafficPct:30,avgInputTok:800,avgOutputTok:400,ctx:16,gpuName:'H100',gpuVram:80,prec:'fp16',tp:4,apiModel:'Claude 3.7 Sonnet',open:false},
    {name:'Complex reasoning',model:'Qwen 2.5 72B',params:72,layers:80,kvHeads:8,headDim:128,attn:'gqa',trafficPct:10,avgInputTok:2000,avgOutputTok:800,ctx:32,gpuName:'H100',gpuVram:80,prec:'fp16',tp:4,apiModel:'GPT-4o',open:false}
  ]
};;

// ── TP CONSTANTS ──────────────────────────────────────────
var TP_MAX_BATCH_TOKENS = 65536;
var TP_THROUGHPUT_EFF   = 0.85;
var TP_HEADROOM         = 1.2;
var TP_OPTIONS          = [1, 2, 4, 8, 16];
var TP_IB_PENALTY       = 1.20;   // cross-node TP>8 penalty
var TP_ETA_WEIGHTS      = 0.87;   // sequential HBM read efficiency
var TP_ALLREDUCE_EFF    = 0.40;   // all-reduce overlap with compute
var TP_SYNC_US          = 10;     // µs per layer barrier
var TP_SYNC_OVERLAP     = 0.30;   // fraction visible in wall clock
var TP_CAL_MOE          = 2.8;  // recalibrated after F4/F5 batch fixes    // empirical: AIC gpt-oss-20b H200 TP=8 +5%
var TP_CAL_DENSE        = 1.5;    // estimated from vLLM benchmarks
var TP_DISAGG_Q_FACTOR  = 0.30;   // llm-d queue reduction (dedicated prefill pool)

// ── QUOTES ───────────────────────────────────────────────────
var TP_QUOTES = [
  {t:'Prefix cache is a TTFT optimization, not a GPU count optimization. Cached tokens skip prefill compute but KV cache still stores all tokens — TPOT is unchanged.', s:'gpu.calc formula spec'},
  {t:'H200 has 43% more HBM bandwidth than H100 — same TFLOPS. For KV-heavy decode workloads, bandwidth is the only number that matters.', s:'NVIDIA H200 datasheet'},
  {t:'At TP=8 vs TP=1, KV reads per GPU shrink 8×. But sync barriers add ~0.3ms regardless. TP=8 is ~4× better TPOT — not 8×. Amdahl\'s Law applies.', s:'gpu.calc analysis'},
  {t:'gpt-oss-20b reads only 3.5B active params per decode step despite 21B in VRAM. This MoE efficiency is why TPOT is competitive with 7B dense models.', s:'MoE inference research'},
  {t:'For ISL=9000 with 80% prefix cache: eff_ISL=1800. TTFT_compute drops 5×. But KV still stores 9000 tokens — decode sees full context every step.', s:'gpu.calc formula spec'},
  {t:'kv_per_token = 2 × layers × kv_heads × head_dim × bytes. For gpt-oss-20b: 72 KB/token. At batch=64 and full ISL=9000: each GPU reads 5.3 GB per decode step at TP=8.', s:'KV cache analysis'},
  {t:'Disaggregated P/D (llm-d) reduces TTFT by isolating prefill from decode queue pressure. For ISL=1800 (80% prefix), P:D ratio is ~1:50 — prefill is cheap.', s:'llm-d architecture'},
  {t:'100M requests/day = 1,157 req/sec. At TPOT=4.4ms and OSL=50: each replica handles 4.5 req/sec. You need 257 replicas × TP=8 = 2,056 GPUs at 80% utilization.', s:'gpu.calc sizing math'},
];
var _tpQI = 0, _tpQT = null;

function tpStartQuotes(){
  _tpQI = Math.floor(Math.random()*TP_QUOTES.length);
  tpShowQuote();
  _tpQT = setInterval(function(){
    var el=document.getElementById('tp-quote-text');
    if(el) el.style.opacity='0';
    setTimeout(function(){
      _tpQI=(_tpQI+1)%TP_QUOTES.length; tpShowQuote();
      var el2=document.getElementById('tp-quote-text');
      if(el2) el2.style.opacity='1';
    },400);
  },3500);
}
function tpStopQuotes(){ if(_tpQT){clearInterval(_tpQT);_tpQT=null;} }
function tpShowQuote(){
  var q=TP_QUOTES[_tpQI];
  var e=document.getElementById('tp-quote-text'), s=document.getElementById('tp-quote-src');
  if(e) e.textContent='"'+q.t+'"';
  if(s) s.textContent='— '+q.s;
}

// ── PURE COMPUTE ENGINE v6.0.0 ────────────────────────────────
// Formula changes vs v6.0.0:
//   avg_ctx = ISL + OSL/2  (KV grows during decode)
//   kv_ratio uses avg_ctx + eff_batch (not ISL + batch)
//   kv_gpu   uses avg_ctx + eff_batch (not ISL + batch)
//   seq_per_sec = eff_batch / (TPOT × OSL)  ← batch amortisation
//   GPU count   = req_s × TPOT × OSL / (eff_batch × tput_eff) × headroom

// ── CAP CONSTANTS ─────────────────────────────────────────
var CAP_OH_NON_TORCH_GB = 0.3;   // CUDA context + drivers (stable across versions)
var CAP_ACT_COEFF = {             // empirical: act_peak = C × batch_tok × hidden × bytes
  'vllm_v017': 0.11,              // vLLM ≥ v0.17 (FlashAttention v2 optimized)
  'vllm_pre17': 0.27,             // vLLM < v0.17 (old attention kernel)
  'trtllm':    0.08,              // TRT-LLM (more aggressive memory optimization)
  'sglang':    0.12,              // SGLang
};
var CAP_GPU_MEM_UTIL   = 0.90;   // gpu_memory_utilization (vLLM default)
var CAP_OH_FLAT_GB     = 11.0;   // legacy fallback only

// ── PRICING DATA ──────────────────────────────────────────
var API_PROVIDERS = [
  // Anthropic — April 2026
  {provider:'Anthropic',model:'Claude Haiku 4.5',  inputPer1M:1.00, outputPer1M:5.00},
  {provider:'Anthropic',model:'Claude Sonnet 4.6', inputPer1M:3.00, outputPer1M:15.00},
  {provider:'Anthropic',model:'Claude Opus 4.6',   inputPer1M:5.00, outputPer1M:25.00},
  // Legacy Anthropic
  {provider:'Anthropic',model:'Claude 3.5 Haiku',  inputPer1M:0.80, outputPer1M:4.00},
  {provider:'Anthropic',model:'Claude 3.7 Sonnet', inputPer1M:3.00, outputPer1M:15.00},
  // OpenAI — April 2026
  {provider:'OpenAI',   model:'GPT-4.1',           inputPer1M:2.00, outputPer1M:8.00},
  {provider:'OpenAI',   model:'GPT-4.1 mini',      inputPer1M:0.40, outputPer1M:1.60},
  {provider:'OpenAI',   model:'GPT-4o',            inputPer1M:2.50, outputPer1M:10.00},
  {provider:'OpenAI',   model:'GPT-4o mini',       inputPer1M:0.15, outputPer1M:0.60},
  {provider:'OpenAI',   model:'o3 mini',           inputPer1M:1.10, outputPer1M:4.40},
  {provider:'OpenAI',   model:'o3',                inputPer1M:10.00,outputPer1M:40.00},
  // Google — April 2026
  {provider:'Google',   model:'Gemini 2.5 Pro',    inputPer1M:1.25, outputPer1M:10.00},
  {provider:'Google',   model:'Gemini 2.5 Flash',  inputPer1M:0.30, outputPer1M:2.50},
  {provider:'Google',   model:'Gemini 2.0 Flash',  inputPer1M:0.10, outputPer1M:0.40},
  // AWS Bedrock
  {provider:'AWS Bedrock',model:'Llama 3.3 70B',   inputPer1M:0.72, outputPer1M:0.72},
];;

// ── GPU HARDWARE DATA ─────────────────────────────────────
var GPU_DATA = [
  // tflops_bf16: dense BF16 TFLOPS (official spec, non-sparse)
  // tflops_fp8:  dense FP8 TFLOPS
  // mfu_prefill: practical MFU for compute-bound prefill (from benchmarks)
  // mfu_bw:      practical memory bandwidth utilisation for decode
  // tdp_w:       thermal design power watts
  // arch:        microarchitecture family
  {name:'A100',     vendor:'nvidia', vram:40,  price:10000, mem_bw:1.56, tpp:6000,  col:'#7ab3e0', tflops_bf16:312,  tflops_fp8:null, mfu_prefill:0.45, mfu_bw:0.87, tdp_w:400,  arch:'ampere'},
  {name:'A100 80GB',vendor:'nvidia', vram:80,  price:15000, mem_bw:2.0,  tpp:10500, col:'#7ab3e0', tflops_bf16:312,  tflops_fp8:null, mfu_prefill:0.45, mfu_bw:0.87, tdp_w:400,  arch:'ampere'},
  {name:'H100',     vendor:'nvidia', vram:80,  price:25000, mem_bw:3.35, tpp:18000, col:'#5b9bd5', tflops_bf16:989,  tflops_fp8:1979, mfu_prefill:0.38, mfu_bw:0.87, tdp_w:700,  arch:'hopper'},
  {name:'H200',     vendor:'nvidia', vram:141, price:32000, mem_bw:4.8,  tpp:25000, col:'#5b9bd5', tflops_bf16:989,  tflops_fp8:1979, mfu_prefill:0.38, mfu_bw:0.87, tdp_w:700,  arch:'hopper'},
  {name:'H20',      vendor:'nvidia', vram:96,  price:12000, mem_bw:4.0,  tpp:7000,  col:'#6aa8dc', tflops_bf16:148,  tflops_fp8:296,  mfu_prefill:0.35, mfu_bw:0.85, tdp_w:500,  arch:'hopper', nvlink_bw_GBs:0},
  {name:'B100',     vendor:'nvidia', vram:192, price:35000, mem_bw:8.0,  tpp:28000, col:'#4285c8', tflops_bf16:1750, tflops_fp8:3500, mfu_prefill:0.42, mfu_bw:0.85, tdp_w:700,  arch:'blackwell'},
  {name:'B200',     vendor:'nvidia', vram:192, price:45000, mem_bw:8.0,  tpp:40000, col:'#3575bc', tflops_bf16:2250, tflops_fp8:4500, mfu_prefill:0.44, mfu_bw:0.85, tdp_w:1000, arch:'blackwell'},
  {name:'B300',     vendor:'nvidia', vram:288, price:60000, mem_bw:10.0, tpp:60000, col:'#2866b0', tflops_bf16:3000, tflops_fp8:6000, mfu_prefill:0.44, mfu_bw:0.83, tdp_w:1400, arch:'blackwell'},
  {name:'B30A',     vendor:'nvidia', vram:120, price:20000, mem_bw:4.0,  tpp:18000, col:'#4d8fd4', tflops_bf16:1500, tflops_fp8:3000, mfu_prefill:0.40, mfu_bw:0.83, tdp_w:600,  arch:'blackwell'},
  {name:'L40S',     vendor:'nvidia', vram:48,  price:14000, mem_bw:0.864,tpp:8000,  col:'#7ab3e0', tflops_bf16:733,  tflops_fp8:1457, mfu_prefill:0.35, mfu_bw:0.82, tdp_w:350,  arch:'ada'},
  {name:'MI250X',   vendor:'amd',    vram:128, price:15000, mem_bw:3.2,  tpp:9000,  col:'#e07878', tflops_bf16:383,  tflops_fp8:null, mfu_prefill:0.22, mfu_bw:0.78, tdp_w:560,  arch:'cdna2'},
  {name:'MI300X',   vendor:'amd',    vram:192, price:25000, mem_bw:5.3,  tpp:22000, col:'#cc4444', tflops_bf16:1307, tflops_fp8:2615, mfu_prefill:0.20, mfu_bw:0.78, tdp_w:750,  arch:'cdna3'},
  {name:'MI325X',   vendor:'amd',    vram:256, price:30000, mem_bw:6.0,  tpp:25000, col:'#c03838', tflops_bf16:1307, tflops_fp8:2615, mfu_prefill:0.20, mfu_bw:0.78, tdp_w:750,  arch:'cdna3'},
  {name:'MI350X',   vendor:'amd',    vram:288, price:40000, mem_bw:8.0,  tpp:34000, col:'#b42020', tflops_bf16:2600, tflops_fp8:4600, mfu_prefill:0.25, mfu_bw:0.80, tdp_w:950,  arch:'cdna4'},
  {name:'MI300A',   vendor:'amd',    vram:128, price:20000, mem_bw:5.2,  tpp:18000, col:'#d96060', tflops_bf16:1307, tflops_fp8:2615, mfu_prefill:0.20, mfu_bw:0.78, tdp_w:760,  arch:'cdna3'},
];;

// ── CORE MATH FUNCTIONS ───────────────────────────────────
// --- capKVCategory ---
function capKVCategory(){
  if(S.kvLoraRank)               return {id:5, label:'Category 5 — MLA (DeepSeek V2/V3/R1) — low-rank KV compression. HF: deepseek-ai/DeepSeek-V3', short:'MLA'};
  if(S.kvArchType==='hybrid_ssm')return {id:4, label:'Category 4 — SSM/Attention Hybrid (Jamba, LFM) — only attention layers have KV. HF: ai21labs/Jamba-v0.1', short:'SSM hybrid'};
  if(S.kvArchType==='hybrid_sliding') return {id:3, label:'Category 3 — Hybrid Sliding/Global (Gemma 3/4) — sliding window + global attention. HF: google/gemma-3-27b-it', short:'Sliding hybrid'};
  if(S.kvArchType==='hybrid_linear') return {id:6, label:'Category 6 — Hybrid Linear Attention — linear attn layers have no KV cache (e.g. RWKV-Hybrid, future models). HF: TBA', short:'Linear hybrid'};
  if(S.isMoE || (S.kvArchType==='moe')) return {id:2, label:'Category 2 — Standard MoE (Mixtral, Qwen2 MoE) — same KV formula as dense. HF: mistralai/Mixtral-8x7B-v0.1', short:'MoE (same KV)'};
  return {id:1, label:'Category 1 — Standard Dense GQA/MHA (Llama, Qwen, Mistral). HF: meta-llama/Llama-3.1-8B', short:'Standard dense'};
}

// --- capBytesKV ---
function capBytesKV(){
  // B1 FIX: was always returning 1 due to wrong fallback
  if(S.kvPrec==='fp8')  return 1;
  if(S.kvPrec==='int8') return 1;
  if(S.kvPrec==='int4') return 0.5;
  return 2; // fp16 default
}

// --- capKVPerToken ---
function capKVPerToken(){
  var bkv = capBytesKV();
  var cat = capKVCategory();

  // Category 5 — MLA (Low-rank KV compression)
  // Formula: (kv_lora_rank + rope_head_dim) × bytes × layers
  // Why less KV: K and V projected to low-rank latent space (kv_lora_rank << hidden_dim)
  // Example model: deepseek-ai/DeepSeek-V3, deepseek-ai/DeepSeek-R1
  if(cat.id===5){
    var ropeHead = S.qkRopeHeadDim || 64;
    return (S.kvLoraRank + ropeHead) * bkv * S.numLayers;
  }

  // Category 4 — SSM/Attention Hybrid
  // Only attention layers have KV cache; SSM (Mamba) layers have O(1) state
  // effLayers = attention-only layer count (kvLayers field)
  // Example model: ai21labs/Jamba-v0.1, microsoft/phi-mamba
  if(cat.id===4){
    var effLayers4 = S.kvLayers || Math.ceil(S.numLayers * 0.5);
    return 2 * effLayers4 * S.numKvHeads * S.headDim * bkv;
  }

  // Category 3 — Hybrid Sliding/Global Attention
  // Global layers: use full context (stored in KV)
  // Sliding layers: only store last W tokens (window size)
  // Per-token average: (global_layers + sliding_layers) × full formula
  // Example model: google/gemma-3-27b-it, google/gemma-3-12b-it
  if(cat.id===3){
    var gLayers = S.kvGlobalLayers  || Math.ceil(S.numLayers * 0.25);
    var sLayers = S.kvSlidingLayers || Math.floor(S.numLayers * 0.75);
    return 2 * (gLayers + sLayers) * S.numKvHeads * S.headDim * bkv;
  }

  // Category 6 — Hybrid Linear Attention
  // Linear attention layers have O(1) state (no KV cache needed)
  // Only standard/full attention layers contribute to KV cache
  // Real examples: RWKV-7-World (hybrid), future hybrid linear models
  // Note: Qwen3-30B-A3B is Cat 2 (MoE), NOT linear hybrid
  if(cat.id===6){
    var effLayers6 = S.kvLayers || Math.ceil(S.numLayers * 0.5);
    return 2 * effLayers6 * S.numKvHeads * S.headDim * bkv;
  }

  // Category 1 — Standard Dense GQA/MHA
  // Example model: meta-llama/Llama-3.1-8B, Qwen/Qwen2.5-7B-Instruct
  // Category 2 — Standard MoE (same KV formula as dense — MoE only affects FFN weights)
  // Example model: mistralai/Mixtral-8x7B-v0.1, Qwen/Qwen1.5-MoE-A2.7B
  var effLayers = S.kvLayers || S.numLayers;
  return 2 * effLayers * S.numKvHeads * S.headDim * bkv;
}

// --- capAvgCtx ---
function capAvgCtx(){
  // avg_ctx = ISL + OSL/2
  // KV grows linearly from ISL to ISL+OSL during decode → average is midpoint
  var isl = S.isl || (S.ctx * 1000);   // tokens (not K)
  var osl = S.osl || 200;
  return isl + osl / 2;
}

// --- capPeakCtx ---
function capPeakCtx(){
  var isl = S.isl || (S.ctx * 1000);
  var osl = S.osl || 200;
  return isl + osl;
}

// --- capKVPerUser ---
function capKVPerUser(){
  var ctxTokens = capAvgCtx();         // USE avg_ctx not ctxMax
  var bkv = capBytesKV();

  // Category 3: Hybrid sliding — split global vs sliding
  if(S.kvArchType==='hybrid_sliding' && S.kvGlobalLayers!=null){
    var gHeads   = S.globalKvHeads || S.numKvHeads;
    var gDim     = S.globalHeadDim || S.headDim;
    var sWin     = S.slidingWindow || 1024;
    var globalB  = S.kvGlobalLayers * ctxTokens * 2 * gHeads * gDim * bkv;
    var slidingB = S.kvSlidingLayers * Math.min(ctxTokens,sWin) * 2 * S.numKvHeads * S.headDim * bkv;
    var raw = (globalB + slidingB) / 1e9;
  } else {
    var raw = capKVPerToken() * ctxTokens / 1e9; // GB
  }

  // Prefix cache: persistent = no VRAM reduction (KV stays resident)
  // Evicting = KV freed after cache hit → reduce by hit rate
  var prefixReduction = (S.cacheType==='evicting') ? (1 - (S.hitrate||0)) : 1.0;
  return raw * prefixReduction;
}

// --- computeTier ---
function computeTier(tier){
  var totalTierUsers=Math.round(SF.totalUsers*tier.trafficPct/100);
  var concurrentUsers=Math.max(1,Math.round(totalTierUsers*(SF.concurrencyFactor||0.10)));

  // API cost (always calculated regardless of self-hosted or API mode)
  var apiProv=API_PROVIDERS.find(function(p){return p.model===tier.apiModel;});
  var queriesPerDay=Math.round(SF.totalUsers*(tier.trafficPct/100)*(SF.queriesPerUserPerDay||100));
  var apiCostYr=0;
  if(apiProv){
    apiCostYr=queriesPerDay*365*(tier.avgInputTok*apiProv.inputPer1M+tier.avgOutputTok*apiProv.outputPer1M)/1e6;
  }

  // ── GPU sizing (self-hosted) ────────────────────────────────────────────────
  // BUG-012: Check if this tier has a self-hosted model configured
  // If apiModel is set but no self-hosted model chosen, GPU count = 0
  var isApiOnly = !tier.model || tier.model === '' || tier.model === 'API only';

  var vram=tier.gpuVram||80;
  var bytesPerParam=tier.prec==='fp16'?2:tier.prec==='fp8'?1:0.5;
  var wGB=tier.params*bytesPerParam;
  var ohGB=vram*0.08;
  var usable=(vram-ohGB)*tier.tp;
  // FIX-028: bytes_kv derived from tier precision, not hardcoded 2
  var bytesKV = tier.prec==='fp8'?1:tier.prec==='int4'?0.5:2;
  // FIX-027: use avg_ctx = ISL + OSL/2, not ctx×1000 (which is peak context, not average)
  var tierISL = tier.avgInputTok  || (tier.ctx*1000) || 2000;
  var tierOSL = tier.avgOutputTok || 200;
  var tierAvgCtx = tierISL + tierOSL / 2;
  var bytesPerTok=2*tier.layers*tier.kvHeads*tier.headDim*bytesKV;
  var kvPU=bytesPerTok*tierAvgCtx/1e9;
  var kvPool=(usable-wGB)*0.95;

  // BUG-021: KV cache theoretical max — apply production realism factor
  // Real capacity is 20-40 users/GPU for most models due to decode bottleneck
  // Theory gives e.g. 237 users but production reality is 20-40
  var uprTheory=Math.max(1,Math.floor(kvPool/Math.max(kvPU,0.001)));

  // Throughput ceiling using continuous batching model (vLLM-style)
  // Look up tok/s from GPU_DATA for the selected GPU, scale by model size
  var gpuEntry = GPU_DATA.find(function(g){
    return tier.gpuName && (tier.gpuName.toUpperCase().indexOf(g.name.toUpperCase())>=0 || g.name.toUpperCase().indexOf(tier.gpuName.toUpperCase().split(' ')[0])>=0);
  });
  var baseTokS = gpuEntry ? gpuEntry.tpp : 18000; // fallback to H100
  // Scale by model size: larger models use more compute per token
  // baseTokS is raw GPU throughput; adjust for model serving overhead
  var tokensPerSecPerGPU = tier.params <= 10  ? Math.round(baseTokS * 0.17) :
                           tier.params <= 30  ? Math.round(baseTokS * 0.083) :
                           tier.params <= 80  ? Math.round(baseTokS * 0.044) :
                                                Math.round(baseTokS * 0.022);
  var avgOutputTokens = tier.avgOutputTok || 200;
  var avgInputTokens  = tier.avgInputTok  || 500;
  // Users/GPU: continuous batching shares decode across requests
  // Effective capacity = (tok/s * target_latency_s * batch_efficiency) / toks_per_request
  var totalToksPerReq = avgInputTokens * 0.3 + avgOutputTokens; // prefill fast, weight output
  var throughputUpr = Math.floor((tokensPerSecPerGPU * 10 * 0.7) / Math.max(totalToksPerReq, 1));

  // Take minimum of KV theory and throughput ceiling, then apply 80% efficiency
  var uprRealistic = Math.max(1, Math.floor(Math.min(uprTheory, throughputUpr) * 0.80));

  // BUG-022: Safety buffer — add 20% headroom for production
  var concurrentWithBuffer = Math.ceil(concurrentUsers * 1.20);

  var replicas=isApiOnly ? 0 : Math.ceil(concurrentWithBuffer/Math.max(uprRealistic,1));
  var totalGPUs=isApiOnly ? 0 : replicas*tier.tp;

  var activeProvider=(typeof PROVIDERS!=='undefined'?PROVIDERS:null)||[];
  var prov=activeProvider.find?activeProvider.find(function(p){return p.active;}):null;
  var cloudCostYr=totalGPUs*(prov?prov.rate:3)*8760;

  return {
    users:totalTierUsers,
    concurrentUsers:concurrentUsers,
    concurrentWithBuffer:concurrentWithBuffer,
    wGB:wGB,ohGB:ohGB,usable:usable,
    kvPU:kvPU,
    uprTheory:uprTheory,
    uprRealistic:uprRealistic,
    replicas:replicas,
    totalGPUs:totalGPUs,
    cloudCostYr:cloudCostYr,
    apiCostYr:apiCostYr,
    queriesPerDay:queriesPerDay,
    isApiOnly:isApiOnly,
  };
}

// --- tpEngine ---
function tpEngine(p) {

  // ── STEP 1: NORMALIZATION ─────────────────────────────────
  var prefix_frac = p.prefix_pct / 100.0;
  var isl_eff     = p.isl * (1 - prefix_frac);   // prefill compute tokens
  var req_per_sec = p.req_day / 86400.0;

  // ── STEP 2: AVERAGE CONTEXT LENGTH ───────────────────────
  // KV cache grows from ISL at step 0 to ISL+OSL at step OSL.
  // Average over the decode phase = ISL + OSL/2.
  // Prefill still uses full ISL (KV must store all input tokens).
  // FIX-024 v2: Evicting cache frees KV after a hit → reduces ISL portion of avg_ctx.
  // OSL tokens are NEVER cached (they are being generated) → OSL/2 never reduced.
  // Persistent cache keeps KV in VRAM (no reduction). Consistent with capKVPerUser().
  // Correct formula: avg_ctx = ISL×(1-hit_rate) + OSL/2
  var prefix_frac_kv = (p.cache_type === 'evicting') ? (p.prefix_pct / 100.0) : 0;
  var avg_ctx        = p.isl * (1 - prefix_frac_kv) + p.osl / 2;  // OSL never cached
  var kv_per_token   = 2 * p.layers * p.kv_heads * p.head_dim * p.bytes_kv;
  var kv_per_request = kv_per_token * avg_ctx;      // avg KV per request during decode

  // ── STEP 3: EFFECTIVE PARAMS FOR PREFILL ─────────────────
  // MoE: attention (dense) + active expert FFN only
  // Dense: use total params
  var eff_params;
  if(p.is_moe && p.total_expert_params > 0){
    var act_exp = (p.total_expert_params / p.num_experts) * p.active_experts;
    eff_params  = p.dense_params + act_exp;
  } else {
    eff_params = p.total_params;
  }

  // ── STEP 4: BATCH CAP (F4) ───────────────────────────────
  // Two constraints: max_batched_tokens budget + scheduler fragmentation
  var max_bt        = p.max_batch_tokens || TP_MAX_BATCH_TOKENS;
  var batch_frag    = p.batch_frag_factor || 0.70;
  var batch_cap_raw = Math.min(p.batch, Math.floor(max_bt / Math.max(isl_eff, 1)));
  // FIX-023: eff_batch_tput NOT capped by concurrency (throughput sizing uses full batch capacity)
  // eff_batch_conc is used only for the concurrency floor replica check
  var eff_batch      = Math.max(1, Math.round(batch_cap_raw * batch_frag));  // throughput sizing
  var eff_batch_conc = Math.max(1, Math.round(Math.min(batch_cap_raw, p.concurrency) * batch_frag)); // concurrency floor only
  var batch_capped   = batch_cap_raw < p.batch;

  // ── STEP 5: KV RATIO + ETA_KV (TP-independent) ───────────
  // Uses avg_ctx (not ISL) and eff_batch (not configured batch)
  var active_bytes = p.active_params * p.bytes_param;
  var kv_ratio     = (kv_per_token * avg_ctx * eff_batch) / active_bytes;
  var eta_kv_base  = p.mfu_bw_base;
  var eta_kv;
  if      (kv_ratio > 10) eta_kv = eta_kv_base * 0.70;
  else if (kv_ratio > 3)  eta_kv = eta_kv_base * 0.85;
  else                    eta_kv = eta_kv_base;
  eta_kv = Math.max(eta_kv, 0.22);

  // ── STEP 6: TTFT (TP-independent) ────────────────────────
  // TTFT_compute: Roofline Model (prefill is compute-bound)
  //   FLOPs = isl_eff × 2 × eff_params (matrix-vector products)
  //   Time  = FLOPs / (GPU FLOPS × MFU)
  //   Reference: Williams et al. 2009 Roofline Model
  var TTFT_compute = (isl_eff * 2 * eff_params) / (p.flops * p.mfu_prefill);

  // TTFT_queue: M/D/1 Queuing Theory
  //   LLM inference has DETERMINISTIC service time (fixed ISL/OSL per batch class)
  //   → M/D/1 queue (Poisson arrivals, Deterministic service) NOT M/M/1
  //   M/D/1 formula: W_q = ρ / (2μ(1-ρ))
  //   where: ρ = λ/μ = utilization, μ = service rate, λ = arrival rate
  //   At low ρ: queue wait ≈ 0. At ρ→1: queue wait → ∞ (hyperbolic blowup)
  //   Reference: Kleinrock 1975, Queueing Systems Vol 1
  //
  //   NOTE: μ here is estimated from eff_batch_conc and TTFT_compute as proxy
  //   for prefill service rate. Full M/D/1 requires knowing seq_per_sec which
  //   is computed in tpot_for_tp() — so we use a pre-sweep estimate here.
  // M/D/1 Queuing Theory (Kleinrock 1975):
  // The queue is served by the SYSTEM of replicas, not a single GPU.
  // Rough replica count: r_est = ceil(req/s / (eff_batch/TTFT × tput_eff))
  // System service rate: μ_sys = μ_single × r_est
  // ρ_sys = λ / μ_sys — this is the meaningful utilization metric.
  var tput_eff_est    = p.tput_eff || TP_THROUGHPUT_EFF;
  var _mu_single      = eff_batch_conc / Math.max(TTFT_compute, 1e-6);
  var _r_est          = Math.max(1, Math.ceil(req_per_sec / (_mu_single * tput_eff_est)));
  var _mu_sys         = _mu_single * _r_est;   // total system prefill rate
  var _rho_prefill    = Math.min(req_per_sec / Math.max(_mu_sys, req_per_sec * 0.01), 0.98);
  // M/D/1: W_q = ρ / (2μ_sys(1-ρ))
  var TTFT_queue_MD1  = _rho_prefill / (2 * _mu_sys * (1 - _rho_prefill));
  // Fallback: old formula (eff_batch / req_s) used as upper bound sanity check
  var TTFT_queue_old  = eff_batch_conc / req_per_sec;
  var TTFT_queue      = Math.min(Math.max(TTFT_queue_MD1, 0), TTFT_queue_old * 2);
  var utilization_prefill = _rho_prefill;  // expose for UI warning (ρ > 0.8 = high load)
  var TTFT_total   = TTFT_compute + TTFT_queue;

  // ── STEP 6b: LITTLE'S LAW CONCURRENCY ────────────────────
  // Little's Law: L = λ × W
  // L = concurrent requests in system
  // λ = arrival rate (req/sec)
  // W = time in system = TTFT + TPOT×OSL (E2E latency)
  // Rough TPOT estimate for Little's Law (TP=1 single-GPU, pre-sweep)
  var _w_tp1  = p.active_params * p.bytes_param / p.bandwidth / (p.eta_weights||TP_ETA_WEIGHTS);
  var _kv_tp1 = kv_per_token * avg_ctx * eff_batch / p.bandwidth / Math.max(eta_kv, 0.22);
  var _cal    = p.is_moe ? (p.cal_moe||TP_CAL_MOE) : (p.cal_dense||TP_CAL_DENSE);
  var _oh_tp1 = Math.max(0.6e-3, 0.1 * Math.max(_w_tp1, _kv_tp1));
  var tpot_est= (Math.max(_w_tp1,_kv_tp1) + _oh_tp1) * _cal;
  var e2e_est = TTFT_total + tpot_est * p.osl;

  // Little's Law implied concurrency
  var littles_concurrency = Math.ceil(req_per_sec * e2e_est);
  // Use max(user input, Little's Law) — never under-provision
  var effective_concurrency = Math.max(p.concurrency, littles_concurrency);
  var littles_warning = littles_concurrency > p.concurrency;  // flag for UI

  // Recompute eff_batch_conc with effective_concurrency
  eff_batch_conc = Math.max(1, Math.round(Math.min(batch_cap_raw, effective_concurrency) * batch_frag));

  // ── STEP 7: PER-TP TPOT + SIZING ─────────────────────────
  function tpot_for_tp(tp){
    var cal   = p.is_moe ? (p.cal_moe || TP_CAL_MOE) : (p.cal_dense || TP_CAL_DENSE);
    var eta_w = p.eta_weights || TP_ETA_WEIGHTS;

    // ── Roofline Model (Williams et al. 2009) ──────────────
    // Decode is memory-bandwidth bound, NOT compute bound.
    // Roofline ridge point = FLOPS / BW (arithmetic intensity threshold)
    //   ridge = p.flops / p.bandwidth  (e.g. H200: 989T/4.8T = 206 FLOP/byte)
    // Arithmetic intensity for decode:
    //   FLOPs  = 2 × active_params × eff_batch  (matmul per decode step)
    //   Bytes  = (active_params + KV_total) × bytes_per_param (memory reads)
    //   If intensity < ridge → MEMORY BOUND (t_kv or t_w dominates)
    //   If intensity > ridge → COMPUTE BOUND (rare, only at batch > 500+)
    var ridge_pt      = p.flops / p.bandwidth;           // FLOP/byte threshold
    var decode_flops  = 2 * p.active_params * eff_batch; // FLOPs per decode step
    var decode_bytes  = (p.active_params / tp + kv_per_token * avg_ctx * eff_batch / tp)
                        * p.bytes_param;
    var arith_intens  = decode_flops / Math.max(decode_bytes, 1);  // FLOP/byte

    // Memory reads per decode step — NEVER multiply bandwidth by TP
    // Weights: active params sharded across TP GPUs
    // KV:      avg_ctx tokens × eff_batch requests, sharded across TP GPUs
    var w_gpu  = p.active_params * p.bytes_param / tp;
    var kv_gpu = kv_per_token * avg_ctx * eff_batch / tp;
    var t_w    = w_gpu  / (p.bandwidth * eta_w);
    var t_kv   = kv_gpu / (p.bandwidth * eta_kv);
    var t_comp = Math.max(t_w, t_kv);           // pipelined — Roofline: take the bottleneck

    // Communication overhead (all-reduce + sync barriers)
    var ibw    = (p.nvlink_bw > 0) ? p.nvlink_bw : p.pcie_bw;
    var ar_b   = 2 * p.hidden_dim * eff_batch * p.bytes_param;
    var tf     = Math.min((tp - 1) / tp, 0.65);
    var t_ar   = (ar_b / ibw) * tf * (p.allreduce_eff || TP_ALLREDUCE_EFF);
    var t_sync = p.layers * (p.sync_us || TP_SYNC_US) * 1e-6 * (p.sync_overlap || TP_SYNC_OVERLAP);
    var oh     = Math.max(0.6e-3, 0.1 * t_comp);

    // ── Universal Scalability Law (Gunther 2002) ───────────
    // USL extends Amdahl's Law with a coherency penalty:
    //   Speedup(N) = N / (1 + α(N-1) + β×N×(N-1))
    //   α = serialization fraction (contention — all-reduce overhead)
    //   β = coherency fraction (cross-GPU data movement penalty)
    //
    // Replaces flat step-function ib_pen (1.0, 1.05, 1.08, 1.10, 1.20)
    // USL gives a smooth, physically-derived degradation curve.
    // α and β are derived from actual comm terms (t_ar, t_sync) relative to t_comp:
    //   α = (t_ar + t_sync) / (t_comp + t_ar + t_sync)   serial fraction
    //   β = α × 0.05   coherency ≈ 5% of serialization (NVLink empirical)
    // USL speedup is then used as an ib_pen multiplier: ib_pen = N / Speedup(N)
    var t_comm_total = t_ar + t_sync;
    var usl_alpha = (tp > 1) ? Math.min((t_comm_total) / Math.max(t_comp + t_comm_total, 1e-9), 0.15) : 0;
    var usl_beta  = usl_alpha * 0.05;
    var usl_speedup = (tp > 1)
      ? tp / (1 + usl_alpha*(tp-1) + usl_beta*tp*(tp-1))
      : 1.0;
    // ib_pen: how much slower than ideal linear speedup
    // e.g. TP=8 ideal=8×, USL=5.3× → ib_pen = 8/5.3 = 1.51
    var ib_pen = (tp > 1) ? (tp / usl_speedup) / tp : 1.0;
    // Apply additional IB penalty for cross-node (TP>8 requires InfiniBand)
    if(tp > 8) ib_pen *= (p.ib_penalty || TP_IB_PENALTY);
    ib_pen = Math.max(1.0, ib_pen);   // never faster than ideal

    var tpot   = (t_comp + t_ar + t_sync + oh) * ib_pen * cal;

    // ── THROUGHPUT (batch amortisation) ──────────────────────
    // Continuous batching: one replica processes eff_batch requests per decode step.
    // seq_per_sec (per replica) = eff_batch / (TPOT × OSL)
    // replicas needed = req_s / (seq_per_sec × tput_eff) × headroom
    // GPUs = replicas × TP   ← this was missing, causing 8× undercount
    var tput_eff    = p.tput_eff || TP_THROUGHPUT_EFF;
    var seq_per_sec = eff_batch / (tpot * p.osl);
    var headroom    = 1 + ((p.buf_pct||20) / 100);  // FIX-032: dynamic buffer from UI
    var reps_tput   = Math.ceil((req_per_sec / (seq_per_sec * tput_eff)) * headroom);
    var gpus_tput   = reps_tput * tp;

    // Concurrency floor (F1): enough replicas for concurrent prefill load
    // FIX-033: Uses effective_concurrency = max(user_input, Little's Law implied)
    var pf_time_s   = TTFT_compute;
    var pf_budget_s = Math.max(pf_time_s * 3.0, 0.5);
    var reps_conc   = Math.max(1, Math.ceil((effective_concurrency * pf_time_s) / pf_budget_s));
    var gpus_conc   = reps_conc * tp;
    var gpus        = Math.max(gpus_tput, gpus_conc);
    var reps        = Math.ceil(gpus / tp);

    // FIX-029: Memory fit uses eff_batch (actual decode batch), not concurrency/tp
    // FIX-034: Use explicit overhead breakdown instead of flat 10% proxy
    //   non_torch (0.3GB stable) + act_peak (version-calibrated)
    //   Consistent with Capacity page capComputeFit() formula
    var w_gb      = p.total_params * p.bytes_param / tp / 1e9;
    var kv_gb     = kv_per_token * avg_ctx * eff_batch / tp / 1e9;
    var non_torch = 0.3;  // CUDA context + drivers (stable)
    // act_peak: version-calibrated coefficient × batch_tokens × hidden × bytes
    var act_coeff = 0.11; // vLLM ≥ v0.17 default
    var act_peak  = act_coeff * (p.max_batch_tokens||2048) * (p.hidden_dim||4096) * p.bytes_param / 1e9;
    act_peak      = Math.max(0.5, Math.min(act_peak, 12.0));
    var oh_gb     = non_torch + act_peak;
    var usable    = p.vram_gb * 0.90;  // gpu_memory_utilization default
    var fits      = (w_gb + kv_gb + oh_gb) < usable;

    var explain;
    if     (tp === 1)  explain = 'Full KV on one GPU. No comm overhead. KV-heavy at large context.';
    else if(tp <= 4)   explain = 'KV sharded '+tp+'×. NVLink comm negligible. Good balance.';
    else if(tp === 8)  explain = 'KV sharded 8×. NVLink within node. Production standard.';
    else               explain = 'KV sharded 16×. Requires InfiniBand/NVSwitch. +20% overhead.';

    return {
      tp:tp, fits:fits, tpot_ms:tpot*1000,
      t_w_ms:t_w*1000, t_kv_ms:t_kv*1000,
      t_comp_ms:t_comp*1000, t_ar_ms:t_ar*1000,
      t_sync_ms:t_sync*1000, oh_ms:oh*1000,
      ib_pen:ib_pen, seq_per_sec:seq_per_sec,
      gpus:gpus, replicas:reps,
      gpus_tput:gpus_tput, gpus_conc:gpus_conc,
      reps_tput:reps_tput, reps_conc:reps_conc,
      pf_budget_s:pf_budget_s,
      kv_gpu_mb:kv_gpu/1e6, w_gb:w_gb, kv_gb:kv_gb,
      kv_bound:t_kv>=t_w,
      // Roofline Model bottleneck classification:
      // 'compute' only when arithmetic intensity > ridge_pt (rare at small batch)
      // 'KV'      when KV read dominates weight read
      // 'weight'  when weight read dominates KV read (common at small ctx + FP8)
      bottleneck: arith_intens > ridge_pt ? 'compute'
                : t_kv >= t_w             ? 'KV'
                :                           'weight',
      tier:tp>8?'multi_node':'single_node',
      explain:explain,
      // USL (Universal Scalability Law)
      usl_alpha:usl_alpha, usl_beta:usl_beta,
      usl_speedup:usl_speedup, ib_pen:ib_pen,
      // Roofline Model
      arith_intens:arith_intens, ridge_pt:ridge_pt,
      roofline_bound:arith_intens < ridge_pt ? 'memory' : 'compute',
    };
  }

  // ── STEP 8: TP SWEEP ─────────────────────────────────────
  var tp_sweep = {};
  TP_OPTIONS.forEach(function(tp){ tp_sweep[tp] = tpot_for_tp(tp); });

  // ── STEP 9: SELECT TP ────────────────────────────────────
  var selected_tp;
  if(p.tp_mode === 'manual'){
    selected_tp = p.tp_value;
  } else {
    var valid = TP_OPTIONS.filter(function(tp){ return tp_sweep[tp].fits; });
    if(!valid.length) valid = [8];
    selected_tp = valid.reduce(function(best,tp){
      return tp_sweep[tp].gpus < tp_sweep[best].gpus ? tp : best;
    }, valid[0]);
  }

  // ── STEP 10: DISAGG (llm-d) ──────────────────────────────
  // BUG-041 FIX: vLLM and llm-d have DIFFERENT effective cache hit rates
  //
  // vLLM (colocated):
  //   Cache is fragmented across N replicas. Requests load-balanced randomly
  //   → same prefix lands on different replicas → cache miss most of the time.
  //   Effective hit rate degrades as sqrt(N) with replica count.
  //   Formula: vllm_hit = user_hit × (1 / sqrt(num_replicas))
  //   Reference: "Prefix Caching for Large Language Models" (2024)
  //
  // llm-d (disaggregated prefill):
  //   Prefix-aware router sends requests with same prefix to same P worker.
  //   KV cache stays resident on that P worker → much higher effective hit rate.
  //   Formula: llmd_hit = user_hit × routing_efficiency (default 0.85)
  //   routing_efficiency: 0.85 conservative, 0.95 with consistent hashing
  var user_hit_rate       = (p.prefix_pct || 0) / 100.0;
  var num_vllm_replicas   = Math.max(1, tp_sweep[selected_tp] ? tp_sweep[selected_tp].reps_tput : 43);
  var routing_eff         = p.routing_efficiency !== undefined ? p.routing_efficiency : 0.85;

  // vLLM: cache fragmented across replicas
  var vllm_effective_hit  = user_hit_rate / Math.sqrt(Math.max(1, num_vllm_replicas));
  vllm_effective_hit      = Math.min(vllm_effective_hit, user_hit_rate);

  // llm-d: prefix-aware routing preserves cache hits
  var llmd_effective_hit  = user_hit_rate * routing_eff;

  // Effective ISL for each mode
  var isl_eff_vllm = p.isl * (1 - vllm_effective_hit);
  var isl_eff_llmd = p.isl * (1 - llmd_effective_hit);

  // TTFT for each mode (Roofline: TTFT_compute = isl_eff × 2 × eff_params / FLOPS×MFU)
  var TTFT_compute_vllm = (isl_eff_vllm * 2 * eff_params) / (p.flops * p.mfu_prefill);
  var TTFT_compute_llmd = (isl_eff_llmd * 2 * eff_params) / (p.flops * p.mfu_prefill);

  // Prefill pool: sized by compute throughput + concurrency floor
  // Decode pool:  same as vLLM decode sizing (tp_sweep already computed)
  function disagg_prefill_gpus(tp){
    // Prefill throughput using llm-d effective ISL (higher cache hit = cheaper prefill)
    var flops_req   = 2 * eff_params * isl_eff_llmd;
    var gpu_flops   = p.flops * p.mfu_prefill * tp;
    var pf_time_s   = flops_req / gpu_flops;
    var rps_rep     = 1.0 / pf_time_s;
    var tput_eff    = p.tput_eff || TP_THROUGHPUT_EFF;
    var gpus_tput   = Math.ceil((req_per_sec / (rps_rep * tput_eff)) * TP_HEADROOM);
    var pf_budget_s = Math.max(pf_time_s * 3.0, 0.5);
    var gpus_conc   = Math.max(1, Math.ceil((effective_concurrency * pf_time_s) / pf_budget_s));
    gpus_conc       = Math.ceil(gpus_conc / tp) * tp;
    return Math.max(gpus_tput, gpus_conc);
  }

  var valid_p  = TP_OPTIONS.filter(function(tp){ return tp_sweep[tp].fits; });
  if(!valid_p.length) valid_p = [8];

  var best_p_tp = valid_p.reduce(function(b,tp){
    return disagg_prefill_gpus(tp) < disagg_prefill_gpus(b) ? tp : b;
  }, valid_p[0]);
  var p_gpus = disagg_prefill_gpus(best_p_tp);

  var best_d_tp = valid_p.reduce(function(b,tp){
    return tp_sweep[tp].gpus < tp_sweep[b].gpus ? tp : b;
  }, valid_p[0]);
  var d_gpus = tp_sweep[best_d_tp].gpus;

  var q_factor          = p.disagg_q_factor !== undefined ? p.disagg_q_factor : TP_DISAGG_Q_FACTOR;
  var TTFT_total_disagg = TTFT_compute + TTFT_queue * q_factor;

  var disagg = {
    prefill_tp:best_p_tp,       prefill_gpus:p_gpus,
    prefill_replicas:Math.ceil(p_gpus / best_p_tp),
    decode_tp:best_d_tp,        decode_gpus:d_gpus,
    decode_replicas:Math.ceil(d_gpus / best_d_tp),
    total_gpus:p_gpus + d_gpus,
    pd_ratio:(d_gpus / Math.max(p_gpus, 1)).toFixed(1),
    ttft_total_ms:TTFT_total_disagg * 1000,
    ttft_compute_ms:TTFT_compute_llmd * 1000,
    ttft_queue_ms:TTFT_queue * q_factor * 1000,
    tpot_ms:tp_sweep[best_d_tp].tpot_ms,
    // BUG-041: cache hit transparency
    llmd_effective_hit:llmd_effective_hit,
    llmd_isl_eff:isl_eff_llmd,
    routing_efficiency:routing_eff,
  };

  return {
    isl_eff:isl_eff, avg_ctx:avg_ctx, req_per_sec:req_per_sec,
    littles_concurrency:littles_concurrency,
    effective_concurrency:effective_concurrency,
    littles_warning:littles_warning,
    e2e_est_ms:e2e_est*1000,
    utilization_prefill:utilization_prefill,
    ttft_queue_md1_ms:TTFT_queue*1000,
    vllm_effective_hit:vllm_effective_hit,
    llmd_effective_hit:llmd_effective_hit,
    isl_eff_vllm:isl_eff_vllm,
    isl_eff_llmd:isl_eff_llmd,
    routing_efficiency:routing_eff,
    num_vllm_replicas:num_vllm_replicas,
    eff_params:eff_params,
    kv_per_token:kv_per_token,
    kv_per_request_mb:kv_per_request / 1e6,
    kv_ratio:kv_ratio, eta_kv:eta_kv,
    eff_batch:eff_batch, eff_batch_conc:eff_batch_conc, batch_capped:batch_capped,
    ttft_compute_ms:TTFT_compute * 1000,
    ttft_queue_ms:TTFT_queue * 1000,
    ttft_total_ms:TTFT_total * 1000,
    selected_tp:selected_tp,
    selected:tp_sweep[selected_tp],
    tp_sweep:tp_sweep,
    disagg:disagg,
    p:p,
  };
}

// ── NODE EXPORT ───────────────────────────────────────────
if(typeof module !== 'undefined') module.exports = {
  tpEngine, computeTier, SF,
  capKVPerToken, capKVPerUser, capBytesKV, capKVCategory, capAvgCtx,
  API_PROVIDERS, GPU_DATA, S,
  CAP_OH_NON_TORCH_GB, CAP_ACT_COEFF, CAP_GPU_MEM_UTIL
};
