#!/usr/bin/env node
'use strict';

/**
 * gpu.calc Release Script
 * ─────────────────────────────────────────────────────────────────────────────
 * Run before every release:
 *   node release.js                    — run tests, block on failure
 *   node release.js --judge            — also run LLM judge
 *   node release.js --skip-tests       — rebuild only (dangerous)
 *
 * What it does:
 *   1. Reads APP_VERSION from index.html
 *   2. Rebuilds gpu_calc_core.js from index.html (always fresh)
 *   3. Runs full test suite
 *   4. Blocks release if any test fails
 *   5. Prints release summary
 */

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const HTML_PATH = path.join(__dirname, 'index.html');
const CORE_PATH = path.join(__dirname, 'gpu_calc_core.js');
const TEST_PATH = path.join(__dirname, 'tests', 'gpu_calc_tests.js');

const SKIP_TESTS = process.argv.includes('--skip-tests');
const WITH_JUDGE = process.argv.includes('--judge');

console.log('\n' + '═'.repeat(70));
console.log('  gpu.calc Release Pipeline');
console.log('═'.repeat(70));

// ── STEP 1: Read version ───────────────────────────────────────────────────
const html = fs.readFileSync(HTML_PATH, 'utf8');
const verMatch = html.match(/APP_VERSION = '([^']+)'/);
const version = verMatch ? verMatch[1] : 'unknown';
console.log(`\n  Version:  v${version}`);
console.log(`  Built:    ${new Date().toISOString()}`);

// ── STEP 2: Rebuild core module ────────────────────────────────────────────
console.log('\n  [1/3] Rebuilding gpu_calc_core.js from index.html...');

function extractJsFn(source, sig) {
  const start = source.indexOf(sig);
  if (start < 0) return null;
  const brace = source.indexOf('{', start);
  let depth = 0, i = brace;
  while (i < source.length) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}') { depth--; if (depth === 0) return source.slice(start, i+1); }
    i++;
  }
  return null;
}

function extractBraceVar(source, sig) {
  const start = source.indexOf(sig);
  if (start < 0) return null;
  const brace = source.indexOf('{', start);
  let depth = 0, i = brace;
  while (i < source.length) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}') { depth--; if (depth === 0) return source.slice(start, i+2); }
    i++;
  }
  return null;
}

function extractBracketVar(source, sig) {
  const start = source.indexOf(sig);
  if (start < 0) return null;
  const brace = source.indexOf('[', start);
  let depth = 0, i = brace;
  while (i < source.length) {
    if (source[i] === '[') depth++;
    else if (source[i] === ']') { depth--; if (depth === 0) return source.slice(start, i+2); }
    i++;
  }
  return null;
}

const pieces = [
  `// AUTO-GENERATED by release.js — do not edit manually\n// Source: index.html v${version}\n// Rebuilt: ${new Date().toISOString()}\n'use strict';\n`,
  "// ── STATE DEFAULTS ────────────────────────────────────────\n" +
    extractBraceVar(html, 'var S = {') + ';\n',
  "// ── FLEET STATE ───────────────────────────────────────────\n" +
    extractBraceVar(html, 'var SF = {') + ';\n',
  "// ── TP CONSTANTS ──────────────────────────────────────────\n" +
    html.slice(html.indexOf('var TP_MAX_BATCH_TOKENS'),
               html.indexOf('\nfunction tpEngine')).trim() + '\n',
  "// ── PRICING DATA ──────────────────────────────────────────\n" +
    extractBracketVar(html, 'var API_PROVIDERS') + ';\n',
  "// ── GPU HARDWARE DATA ─────────────────────────────────────\n" +
    extractBracketVar(html, 'var GPU_DATA') + ';\n',
  "// ── CORE MATH FUNCTIONS ───────────────────────────────────\n" +
  [
    ['capKVCategory', 'function capKVCategory(){'],
    ['capBytesKV',    'function capBytesKV(){'],
    ['capKVPerToken', 'function capKVPerToken(){'],
    ['capAvgCtx',     'function capAvgCtx(){'],
    ['capPeakCtx',    'function capPeakCtx(){'],
    ['capKVPerUser',  'function capKVPerUser(){'],
    ['computeTier',   'function computeTier(tier){'],
    ['tpEngine',      'function tpEngine(p) {'],
  ].map(([name, sig]) => `// --- ${name} ---\n${extractJsFn(html, sig)}`).join('\n\n'),
  "\n// ── NODE EXPORT ───────────────────────────────────────────\n" +
  "if(typeof module !== 'undefined') module.exports = {\n" +
  "  tpEngine, computeTier, SF,\n" +
  "  capKVPerToken, capKVPerUser, capBytesKV, capKVCategory, capAvgCtx,\n" +
  "  API_PROVIDERS, GPU_DATA, S\n" +
  "};\n"
];

fs.writeFileSync(CORE_PATH, pieces.join('\n'));
console.log(`  ✓ gpu_calc_core.js rebuilt (${fs.statSync(CORE_PATH).size.toLocaleString()} bytes)`);

// Verify it loads
try {
  delete require.cache[require.resolve(CORE_PATH)];
  const c = require(CORE_PATH);
  const fnCount = ['tpEngine','computeTier','capKVPerToken','capKVPerUser'].filter(f => typeof c[f] === 'function').length;
  console.log(`  ✓ Core module loads cleanly (${fnCount}/4 functions, ${c.API_PROVIDERS.length} providers, ${c.GPU_DATA.length} GPUs)`);
} catch(e) {
  console.error(`  ✗ Core module failed to load: ${e.message}`);
  process.exit(1);
}

// ── STEP 3: Run tests ──────────────────────────────────────────────────────
let passCount = '?';
if (SKIP_TESTS) {
  console.log('\n  [2/3] Tests SKIPPED (--skip-tests flag)');
  console.log('\n  ⚠  WARNING: Releasing without test validation');
} else {
  console.log('\n  [2/3] Running test suite...');
  const judgeFlag = WITH_JUDGE ? ' --judge' : '';
  try {
    const output = execSync(`node "${TEST_PATH}"${judgeFlag}`, { encoding: 'utf8' });
    // Extract results line
    const resultsLine = output.split('\n').find(l => l.includes('RESULTS:'));
    const _pm = output.match(/(\d+) passed/);
    passCount = _pm ? _pm[1] : '?';
    console.log(`  ${resultsLine?.trim() || 'Tests completed'}`);
    
    // Count failures
    const failMatch = output.match(/(\d+) failed/);
    const failCount = failMatch ? parseInt(failMatch[1]) : 0;
    if (failCount > 0) {
      console.log('\n  ✗ RELEASE BLOCKED — tests failed:');
      output.split('\n').filter(l => l.includes('  ✗')).forEach(l => console.log('   ', l.trim()));
      process.exit(1);
    }
    console.log('  ✓ All tests passed — release unblocked');
  } catch(e) {
    console.error('\n  ✗ RELEASE BLOCKED — test run failed');
    console.error(e.stdout || e.message);
    process.exit(1);
  }
}

// ── STEP 4: Release summary ────────────────────────────────────────────────
console.log('\n  [3/3] Release summary');

// Count bugs fixed (from registry in HTML)
const fixedBugs = (html.match(/FIXED in v/g) || []).length;
const openBugs  = (html.match(/\| OPEN\n/g) || []).length;

// Get file size
const htmlSize = fs.statSync(HTML_PATH).size;

console.log(`
  ┌─────────────────────────────────────────────┐
  │  gpu.calc v${version.padEnd(34)}│
  │  File size:  ${(htmlSize/1024).toFixed(0).padStart(6)} KB                         │
  │  Bugs fixed: ${String(fixedBugs).padStart(6)} in registry                  │
  │  Open bugs:  ${String(openBugs).padStart(6)} tracked                       │
  │  Test suite: ${passCount} assertions, 6 layers     │
  │  LLM judge:  ${WITH_JUDGE ? 'enabled' : 'disabled (use --judge)       '}          │
  └─────────────────────────────────────────────┘

  ✓ READY TO RELEASE v${version}
`);
